config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :chefs, except: [:new, :destroy]
  get '/register/', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2>This is the homepage for the Udemy myRecipes demonstration app</h2>

  <%= link_to "Sign-up", register_path, class: "btn btn-lg btn-success"%>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse recipe listings", recipes_path, class: "btn btn-warning btn-small"%></p>
  </div>
  
  <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">Add/Update your recipes, create reviews, like/dislike recipes and much more...</h2>
    <p><%= link_to "Sign in to your account", login_path, class: "btn btn-warning btn-small"%></p>
  </div>
  
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse recipe listings","", class: "btn btn-warning btn-small"%></p>
  </div>
</div>